# Generated by Django 2.1 on 2019-02-27 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='art/')),
                ('description', models.TextField()),
                ('size1', models.CharField(blank=True, max_length=15)),
                ('size2', models.CharField(blank=True, max_length=15)),
                ('size3', models.CharField(blank=True, max_length=15)),
                ('size4', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=15)),
                ('details', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='attachment/')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Art')),
            ],
        ),
    ]
