# Generated by Django 2.1 on 2019-03-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190302_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='rname',
            field=models.CharField(default='ram', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='size',
            field=models.CharField(choices=[('5"x5"', '5x5'), ('10"x10"', '10x10')], max_length=15),
        ),
    ]
