# Generated by Django 2.1 on 2019-03-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190302_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='rname',
        ),
    ]
