# Generated by Django 2.1 on 2019-03-07 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_commission_rname'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commission',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commission',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commission',
            name='sub_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
