# Generated by Django 2.1 on 2019-03-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190307_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='pub_date',
            field=models.DateField(verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='done',
            field=models.BooleanField(default=False, verbose_name='submited?'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='pub_date',
            field=models.DateField(verbose_name='asked on'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='sub_date',
            field=models.DateField(verbose_name='submited on'),
        ),
    ]
